name: Deploy Documentation Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_DOCS_PATH: ${{ secrets.FTP_DOCS_PATH }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y lftp
          python -m pip install --upgrade pip
          python -m pip install myst-parser sphinx sphinx-autodoc-typehints

      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      - name: Deploy documentation via FTP
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
            mirror -R -P 5 docs/build $FTP_DOCS_PATH;
            bye;
          "
